#!/bin/bash

# project.test_env
# ${JOB_NAME} is a Jenkins var


IFS="." read -ra array <<< "${JOB_NAME}"
TEST_ENV=${array[1]}
docker pull firefoxtesteng/kinto-integration-tests:latest
docker run -e TEST_ENV=$TEST_ENV firefoxtesteng/kinto-integration-tests:latest
